### ISSUE TITLE
lines not rendered due to stroke-width set to 0

### ISSUE THREAD

**Issue by take4mats** [Seao/grav-plugin-diagrams#4] opened 2018-02-17 16:08 UTC
I'm using v1.0.1 and found the example sequence diagram doesn't render lines and arrows correctly.
It seems applied CSS is below, around line 130 in `css/mermaid.css`.
```css
.grid path {
  stroke-width: 0;
}
```
When I set `stroke-width` to 1, it did render.  Is it a bug?

**Comment by Seao** [comment] 2018-02-18 18:16
Hi @take4mats,

I didn't succeed to reproduce your issue with a clean install, the sequence diagram seems to work correctly. However I had issues with two Mermaid diagrams in the same page, there are some conflicts with `classDef`, I don't know if it's linked.

Could you send your code and a screenshot ?

**Comment by take4mats** [comment] 2018-02-19 11:12
Hi @Seao 
FYI: I'm using Antimatter v 2.1.2 as the theme, and the Diagram v1.0.1 is installed via Admin panel.

Here are screenshots before/after I patched:
![original](https://user-images.githubusercontent.com/1111582/36374965-a6e1174c-15b0-11e8-957c-6239cd2fa626.png)
![patched](https://user-images.githubusercontent.com/1111582/36374967-a7077d42-15b0-11e8-8359-d60d438cb8d8.png)

**Comment by Seao** [comment] 2018-02-20 22:16
Thanks for these informations, I managed to reproduce the bug 👍 

This issue is happening with `item` page template of Antimatter theme, because the post content is wrapped in a div with `blog-content-item grid pure-g-r` classes that are inferring with the CSS you pointed out.

I committed a fix on master branch, please could you check if everything is working as expected on you site ? I will release the new plugin version tomorrow and submit it to GPM.

**Closed as completed by Seao** 2018-02-20 22:16 UTC

**Comment by take4mats** [comment] 2018-02-20 23:04
Thanks a lot @Seao for such quick action! Now I see it works well 👏
