### ISSUE TITLE
Quark-Theme Interference

### ISSUE THREAD

**Issue by cubuzz** [Seao/grav-plugin-diagrams#7] opened 2018-03-27 14:55 UTC
When creating a diagram on a page which uses the Quark Theme, it causes a grey overlay on the entire page.

**Comment by Seao** [comment] 2018-04-06 15:38
Hi @Snackomat,

I managed to reproduce this issue. Indeed mermaid css has unexpected comportements by interfering with elements other than diagrams. I committed changes to restrict the css to diagrams : https://github.com/Seao/grav-plugin-diagrams/tree/overlay-mermaid-css

Could you please install this version modified and check if these modifications fix your issue ?

**Comment by cubuzz** [comment] 2018-04-08 08:02
As sorry as I am, my friend, I am still able to reproduce that error using flow diagrams. Mermaids also don't work.

**Comment by AxelRHD** [comment] 2018-06-27 09:17
Same problem here. Gray overlay on every page.

**Comment by AxelRHD** [comment] 2018-06-27 09:28
Problem solved. In the grav GPM package download there is still the old wrong css file. Downloaded it from GIT and now it works.

**Comment by kevinJread** [comment] 2019-01-29 23:41
Fixed by removing the .section overlay at line 94 

```
/** Section styling */
.section {
  stroke: none;
  noopacity: 0.2;
}
```

**Comment by Goutte** [comment] 2019-03-16 09:52
@Seao I can confirm that with a brand-new Grav installation, this issue still happens.

The `div.section` is still widely used in templates instead of the more modern `section` tag.

PR follows :tada:

**Comment by joss2133** [comment] 2019-04-16 13:37
Same issue here... it seems a greate plugin but not working... any idea if it is going to be fixxed?

**Comment by Seao** [comment] 2019-04-16 14:24
Hi there, thanks for the interest on this plugin. Unfortunately I didn't had enough time for working on it since a while, sorry for that. I will take a look on ongoing issues, @Goutte's pull request, and release a new version in coming days to fix compatibility problems with Grav themes. I'll keep you informed :+1:

**Comment by Goutte** [comment] 2019-04-16 23:50
I'm not too fond of my PR.  What I'm using in practice is a simple `svg .section` instead of `section` since it's the only collision I observed.  It is a confounding bug for users, though, since it happens with a fresh install.

**Comment by joss2133** [comment] 2019-04-16 23:54
Ha ok. 2 questions if I could ask, PR stands for? and could you explain a bit the svg .section?? thanks in advance!

**Comment by Goutte** [comment] 2019-04-17 05:17
Pull Request.

Find the file `mermaid.css`, and edit the line with `.section {` to `svg .section {`.
It'll make sure the reduced opacity is only applied to elements inside a `svg` tag.

**Closed as completed** 2019-04-23 21:17 UTC

**Comment by joss2133** [comment] 2019-04-24 02:10
Thank you very much! with the new update it works like a charm! Thanks for all your effort
